defaults:
  - _self_
  - algorithm: ppo
  - environment: gymnasium/pendulum
  - search_space: ppo_rs
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
  - override hydra/help: mighty_help
  - override hydra/sweeper: HyperPBT        # use Hypersweeper’s RandomSearch

runner: standard
debug: false
seed: 0
output_dir: sweep_pbt
wandb_project: null
tensorboard_file: null
experiment_name: mighty_experiment

algorithm_kwargs: {}

# Training
eval_every_n_steps: 1e4  # After how many steps to evaluate.
n_episodes_eval: 10
checkpoint: null  # Path to load model checkpoint
save_model_every_n_steps: 5e5

hydra:
  sweeper:
    budget: 100000
    budget_variable: 100000
    loading_variable: load
    saving_variable: save
    sweeper_kwargs:
      optimizer_kwargs:
        population_size: 10
        config_interval: 1e4
      checkpoint_tf: true
      load_tf: true
    search_space: ${search_space}
  run:
    dir: ${output_dir}/${experiment_name}_${seed}
  sweep:
    dir: ${output_dir}/${experiment_name}_${seed}