hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    default: 0.0003
    log: true
  algorithm_kwargs.gamma:
    type: uniform_float
    lower: 0.9
    upper: 0.9999
    log: false
  algorithm_kwargs.batch_size:
    type: categorical
    choices: [32, 64, 128, 256]