hyperparameters:
  algorithm_kwargs.learning_rate:
    type: uniform_float
    lower: 0.000001
    upper: 0.01
    log: true
  algorithm_kwargs.batch_size:
    type: categorical
    choices: [32, 64, 128, 256]